# Generated by Django 4.2.1 on 2023-07-31 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='heard_from',
            field=models.CharField(choices=[('I', 'Instagram'), ('F', 'Facebook'), ('OS', 'Online Search'), ('FF', 'Friends / Family'), ('O', 'Other')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
