version: "3.8"

services:
 app:
  build: .
  volumes:
   - .:/backend
  ports:
   - 8000:8000
  image: app:backend
  container_name: my_backend_container
  command: >
   sh -c "python manage.py makemigrations && \
          python manage.py migrate && \
          python manage.py runserver 0.0.0.0:8000"