# Generated by Django 4.2.1 on 2023-07-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='cakes/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('event_details', models.CharField(max_length=300)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('pastery', models.CharField(max_length=50)),
                ('cake_size', models.CharField(max_length=100)),
                ('cake_size_other', models.CharField(max_length=100)),
                ('cake_flavor', models.CharField(max_length=100)),
                ('cake_flavor_other', models.CharField(max_length=100)),
                ('cake_frosting', models.CharField(max_length=100)),
                ('cake_frosting_other', models.CharField(max_length=100)),
                ('cake_design', models.CharField(max_length=200)),
                ('cake_color', models.CharField(max_length=100)),
                ('cake_message', models.CharField(max_length=100)),
                ('cake_inspiration_file', models.CharField(max_length=100)),
                ('cake_additions', models.CharField(max_length=300)),
                ('cake_treats', models.CharField(max_length=100)),
                ('cake_treats_other', models.CharField(max_length=100)),
                ('cake_treat_details', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=50)),
                ('delivery_pickup', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=100)),
                ('pickup_time', models.CharField(max_length=100)),
                ('pickup_time_other', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_method_other', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
            ],
        ),
    ]
