# Generated by Django 3.2.22 on 2024-01-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_cake_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
