# Generated by Django 4.2.1 on 2023-06-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_remove_cake_image_cake_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='img_url',
        ),
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
