# Generated by Django 4.2.1 on 2023-06-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_remove_cake_img_url_cake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, upload_to='cakes/'),
        ),
    ]
